# Generated by Django 4.0.1 on 2022-01-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'discount categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('percent', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='discounts_app.discountcategory')),
            ],
        ),
    ]
