# Generated by Django 4.0.1 on 2022-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
