# Generated by Django 4.0.1 on 2022-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
