# Generated by Django 4.0.1 on 2022-02-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0002_alter_discount_amount_alter_discount_percent'),
        ('banners_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_banner', to='discounts_app.discount', verbose_name='discount_banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='banner_description'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/content/home/banners', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=25, null=True, verbose_name='banner_title'),
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
    ]
