# Generated by Django 4.0.1 on 2022-01-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods_app', '0002_alter_productcategory_options'),
        ('discounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='discounts_app.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='goods_app.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='stores_app.seller')),
            ],
        ),
    ]
