# Generated by Django 4.0.1 on 2022-01-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproduct',
            name='name',
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
