# Generated by Django 4.0.1 on 2022-02-08 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0005_alter_product_image'),
        ('discounts_app', '0002_alter_discount_amount_alter_discount_percent'),
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerproduct',
            options={'verbose_name': 'product in shop', 'verbose_name_plural': 'products in shop'},
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='discounts_app.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price_after_discount'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='goods_app.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='stores_app.seller', verbose_name='seller'),
        ),
    ]
