# Generated by Django 4.0.1 on 2022-02-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_app', '0002_alter_sellerproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'seller', 'verbose_name_plural': 'sellers'},
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=25, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
