# Generated by Django 4.0.1 on 2022-02-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=255, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('comments', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25, null=True)),
                ('content', models.TextField(max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='goods_app.product')),
            ],
        ),
    ]
