# Generated by Django 4.0.1 on 2022-01-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'product categories'},
        ),
    ]
