# Generated by Django 4.0.1 on 2022-02-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'good', 'verbose_name_plural': 'goods'},
        ),
        migrations.AlterField(
            model_name='product',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='average_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods_app.productcategory', verbose_name='good_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=25, null=True, verbose_name='good_code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.IntegerField(null=True, verbose_name='amount_of_comments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='good_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='good_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='good_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, verbose_name='good_slug'),
        ),
    ]
